### PR TITLE
move all sectors to subfolders

### PR DESCRIPTION
**Pull request by Jeniffere**
move all sectors to subfolders

### CODE REVIEW

**Comment by Jeniffere** [comment]
Ich glaube eure Änderungen haben ready_to_rock bei mir kaputt gemacht oder muss ich jetzt noch irgendwas machen?

E:\LocalZero\Code\main\localzero-generator-core>python devtool.py ready_to_rock
Traceback (most recent call last):
  File "E:\LocalZero\Code\main\localzero-generator-core\devtool.py", line 153, in <module>
    main()
  File "E:\LocalZero\Code\main\localzero-generator-core\devtool.py", line 150, in main
    args.func(args)
  File "E:\LocalZero\Code\main\localzero-generator-core\commands\cmd_ready_to_rock.py", line 6, in cmd_ready_to_rock
    subprocess.run(["poetry", "run", "pyright"], check=True)
  File "C:\Users\Jenny\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Jenny\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Jenny\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

**Comment by bgrundmann** [comment]
@curiousleo Do you have an idea what's going on?  @Jeniffere you did open a poetry shell first?

**Comment by Jeniffere** [comment]
I did open a poetry shell and to be up to date I also did poetry install

**Comment by curiousleo** [comment]
Sorry, gerade erst gesehen.

@Jeniffere kannst du diese zwei Kommandos ausprobieren und den Output hier anzeigen?

- `poetry run pyright`
- `poetry run python devtool.py ready_to_rock`

**Comment by bgrundmann** [comment]
@Jeniffere assuming #213 fixes the ready to rock on windows problem, we can then:

- merge #213 -> main
- merge main -> #212, run ready to rock and put the output here.
- (assuming a good ready to rock) merge #212 -> main

**Comment by Jeniffere** [comment]
No configuration file found.
pyproject.toml file found at E:\LocalZero\Code\main\localzero-generator-core.
Loading pyproject.toml file at E:\LocalZero\Code\main\localzero-generator-core\pyproject.toml
Assuming Python platform Windows
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath E:\LocalZero\Code\main\localzero-generator-core\typings is not a valid directory.
Searching for source files
Found 66 source files
0 errors, 0 warnings, 0 informations 
Completed in 7.704sec
==================================================================== test session starts =====================================================================
platform win32 -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: E:\LocalZero\Code\main\localzero-generator-core
plugins: cov-3.0.0
collected 16 items

tests\test_end_to_end.py ...........                                                                                                                    [ 68%]
tests\test_entries.py .                                                                                                                                 [ 75%]
tests\test_refdata.py ....                                                                                                                              [100%]

===================================================================== 16 passed in 9.15s ===================================================================== 
Trim Trailing Whitespace.................................................Passed
Mixed line ending........................................................Passed
Check for case conflicts.................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
Don't commit to branch...................................................Passed
black....................................................................Passed
You are ready to rock and save the climate at 756ec2e0ada06ba67021e075bb8af75fd7256d35, but don't forget to copy paste the above into your pull request

**Comment by Jeniffere** [comment]
All problems solved.

**Pull request merged**
