### PR TITLE
Update Pyright: 0.0.13post0 -> 1.1.234

### PR DESCRIPTION
**Pull request by curiousleo**
I could not find the release date for Pyright 0.0.13 [in the repo](https://github.com/Microsoft/pyright).

Version 1.0.0 was released in March 2019: https://github.com/Microsoft/pyright/tree/1.0.0.

So ... time to update :) Version 1.1.234 was released on March 30th, 2022.

### CODE REVIEW

**Comment by curiousleo** [comment]
@bgrundmann I don't see `pyright` being triggered anywhere in CI or in the pre-commit hook. I may well have missed something though. How is `pyright` currently being used?

**Comment by bgrundmann** [comment]
Your description highlights that you misunderstood something. The version numbers of pyright (the typescript written npm package that contains the checker aka: https://github.com/microsoft/pyright) and the version number of the python package that wraps it (https://pypi.org/project/pyright/) used to be distinct because they were actually two separate projects by different people.

Now it looks like microsoft (2 days ago) realized that it is better to make the projects match more.  So this is unlikely to actually change much in terms of what version of pyright everybody uses.  It's also worth noting that all the windows users among us, had little luck with the pyright package and had to install node + the npm package manually. Vs on linux (where the website runs on) and mac (what I use) the package worked just fine.

**Comment by bgrundmann** [comment]
That all said it's of course a good idea to update when upstream updates. I'll try this out in the next few days and merge it. Thanks.

**Comment by curiousleo** [comment]
> Your description highlights that you misunderstood something. The version numbers of pyright (the typescript written npm package that contains the checker aka: https://github.com/microsoft/pyright) and the version number of the python package that wraps it (https://pypi.org/project/pyright/) used to be distinct because they were actually two separate projects by different people.

You're right, I was confused about how those versions related. Thanks for the explanation.

> Now it looks like microsoft (2 days ago) realized that it is better to make the projects match more. So this is unlikely to actually change much in terms of what version of pyright everybody uses.

When I run `python run pyright --version`, I get the same result on `main` and on this branch. So I think this change does not actually have any effect on what version of `pyright` is executed -- it was the most recent one before, and still is with this PR.

That's in line with what the `pyright` Python package docs say:

> We also automatically upgrade the pyright npm package to it's latest version on every run, see below for how to change this behaviour.

---

> That all said it's of course a good idea to update when upstream updates. I'll try this out in the next few days and merge it. Thanks.

Sounds good, thanks.

**Comment by bgrundmann** [comment]
Okay this seems to work. I'm merging this but I'm curious to hear from our windows users.  @Jeniffere can you make sure you run poetry install after updating to this version, and then tell us if pyright works or not?

**Comment by Jeniffere** [comment]
I get the same error on ready_to_rock:

E:\LocalZero\Code\main\localzero-generator-core>python devtool.py ready_to_rock
Traceback (most recent call last):
  File "E:\LocalZero\Code\main\localzero-generator-core\devtool.py", line 153, in <module>
    main()
  File "E:\LocalZero\Code\main\localzero-generator-core\devtool.py", line 150, in main
    args.func(args)
  File "E:\LocalZero\Code\main\localzero-generator-core\commands\cmd_ready_to_rock.py", line 6, in cmd_ready_to_rock
    subprocess.run(["poetry", "run", "pyright"], check=True)
  File "C:\Users\Jenny\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Jenny\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Jenny\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

**Comment by Jeniffere** [comment]
But the error from ready_to_rock seems not to be related to pyright.

If I comment this out:
`# subprocess.run(["poetry", "run", "pyright"], check=True)`

The next line crashes:
`subprocess.run(["poetry", "run", "pytest"], check=True)`

**Comment by Jeniffere** [comment]
Sorry, I don't have time right now to investigate further ...

**Comment by Jeniffere** [comment]
The pyright update should be ok.

This works alright on main:
`subprocess.run(["pyright"], check=True)`

**Comment by curiousleo** [comment]
(See https://github.com/GermanZero-de/localzero-generator-core/pull/212#issuecomment-1086637061 and following comments.)

**Pull request merged**
