### PR TITLE
Extract main dataclass per sector

### PR DESCRIPTION
**Pull request by Jeniffere**
PS E:\LocalZero\Code\main\localzero-generator-core> python devtool.py ready_to_rock
WARNING: there is a new pyright version available (v1.1.255).
Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`

No configuration file found.
pyproject.toml file found at E:\LocalZero\Code\main\localzero-generator-core.
Loading pyproject.toml file at E:\LocalZero\Code\main\localzero-generator-core\pyproject.toml
Assuming Python platform Windows
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath E:\LocalZero\Code\main\localzero-generator-core\typings is not a valid directory.
Searching for source files
Found 94 source files
0 errors, 0 warnings, 0 informations 
Completed in 9.638sec
==================================================================== test session starts =====================================================================
platform win32 -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: E:\LocalZero\Code\main\localzero-generator-core
collected 16 items

tests\test_end_to_end.py ...........                                                                                                                    [ 68%]
tests\test_entries.py .                                                                                                                                 [ 75%]
tests\test_refdata.py ....                                                                                                                              [100%]

====================================================================== warnings summary ====================================================================== 
generatorcore\residences2030\__init__.py:1
  E:\LocalZero\Code\main\localzero-generator-core\generatorcore\residences2030\__init__.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================================================== 16 passed, 1 warning in 11.86s =============================================================== 
Trim Trailing Whitespace.................................................Passed
Mixed line ending........................................................Passed
Check for case conflicts.................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
Don't commit to branch...................................................Passed
black....................................................................Passed
You are ready to rock and save the climate at 1764a44563ef241a6d69b95416b63cef7f64b7b1, but don't forget to copy paste the above into your pull request
PS E:\LocalZero\Code\main\localzero-generator-core>

### CODE REVIEW

**Comment by Jeniffere** [comment]
I didn't extract the dataclasses for electricity2030, because I didn't want to create a conflict for @bgrundmann

**Comment by Ultramarin95** [comment]
@Jeniffere So basically you pulled out all "@dataclass"-taged classes into seperate files? Whats the point of this (honest question)? Is this part of a style guide or something similar?

**Comment by Jeniffere** [comment]
It helps me to get a better overview of the code und gives it more structure. And yes, it is a common principle of clean code to avoid to large files ... divide an conquer ;)

My target was to extract the dataclasses like a18.py which are kind of the interface of the sector. I wanted to make it more clear, what each sector calculates and returns.

To do that, I needed to extract all other dataclasses as well ... otherwise there would be a circular dependendcy.

The end goal is to give each sector a structure like industry2018 or transport2018. This is just one step in this direction.

**Comment by bgrundmann** [comment]
This is not a fully formed thought, but a hunch: I think medium term it might even be a good idea to separate the calculations and the dataclasses completely.  That is instead of the current where we have e.g. Transport.calc, we would have calc_transport(...) -> Transport. Why? Because than we could even put all the types into a separate library and offer a python library to call our JSON RPC.

**Pull request merged**
