### PR TITLE
Change bisko calculation

### PR DESCRIPTION
**Pull request by Ultramarin95**
This changes the Bisko calculation from "directly importing CO2 Emissions from Einflussbilanz-Sectors to the Bisko sectors" to "importing energy consumptions from Einflussbilanz-sectors to Bisko sectors and then calculating CO2 Emissions with emission factors in the bisko sectors". This is supposed to make the bisko calculation more intuitive.

### CODE REVIEW

**Comment by Ultramarin95** [comment]
This is ready to rock now
```
D:\Dateien\germanZero\ExcelToPython\g2p2\localzero-generator-core>python devtool.py ready_to_rock
WARNING: there is a new pyright version available (v1.1.255 -> v1.1.261).
Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`

No configuration file found.
pyproject.toml file found at D:\Dateien\germanZero\ExcelToPython\g2p2\localzero-generator-core.
Loading pyproject.toml file at D:\Dateien\germanZero\ExcelToPython\g2p2\localzero-generator-core\pyproject.toml
Assuming Python platform Windows
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath D:\Dateien\germanZero\ExcelToPython\g2p2\localzero-generator-core\typings is not a valid directory.
Searching for source files
Found 101 source files
pyright 1.1.255
0 errors, 0 warnings, 0 informations
Completed in 24.285sec
================================================= test session starts =================================================
platform win32 -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: D:\Dateien\germanZero\ExcelToPython\g2p2\localzero-generator-core
plugins: cov-3.0.0, typeguard-2.13.3
collected 28 items

tests\test_devtool_commands.py ............                                                                      [ 42%]
tests\test_end_to_end.py ...........                                                                             [ 82%]
tests\test_entries.py .                                                                                          [ 85%]
tests\test_refdata.py ....                                                                                       [100%]

================================================= 28 passed in 16.32s =================================================
Trim Trailing Whitespace.................................................Passed
Mixed line ending........................................................Passed
Check for case conflicts.................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
Don't commit to branch...................................................Passed
black....................................................................Passed
You are ready to rock and save the climate at 640ca653eabb579cfab92875fe4e67ebc5fcee42, but don't forget to copy paste the above into your pull request
```

**Comment by Ultramarin95** [comment]
Generally this can be merged. However, i saw that one of @Jeniffere last Merge Requests left a bug in the test commands. Right now pytest always updates the expectations in main. I fixed this by commenting out the tests. I dont know what to merge first. This thing here or a potential bugfix from Jenny :)

**Comment by bgrundmann** [comment]
We should fix our setup first. I can have a look tomorrow if @Jeniffere doesn’t beat me to it

**Comment by bgrundmann** [comment]
@Ultramarin95 Question: Your description makes it sound like this is just a different way to calculate the same result.  But looking at the updated expectations the values do often differ (and sometimes by ~ 50%).  Is that expected?

**Comment by bgrundmann** [comment]
> We should fix our setup first. I can have a look tomorrow if @Jeniffere doesn’t beat me to it

Just for the record that was done.

**Comment by Ultramarin95** [comment]
(https://github.com/GermanZero-de/localzero-generator-core/pull/259#issuecomment-1192246739)
Yes this is expected. And my first comment might be misleading. The new way of calculating the emissions changes single emission values quite a lot (It more or less distributes the emissions precisly instead of distributing them by energy share in the sectors). The total amount of emitted CO2e (CO2e pb + cb) should remain more or less constant.

**Pull request merged**
