### PR TITLE
Year baseline as new argument

### PR DESCRIPTION
**Pull request by Jeniffere**
year_baseline is now (similar to year_ref and year_target) an argument of the generator.
This makes it more visible that the year_baseline is currently 2022 and not really the current year and therefore should be updated at least to 2023 in the near future.

### CODE REVIEW

**Comment by Jeniffere** [comment]
@bgrundmann: I think, there are some further changes in the explorer necessary, because I added the year_baseline to the rpcs as well?! Could you look into the explorer?

**Comment by Jeniffere** [comment]
python devtool.py ready_to_rock
WARNING: there is a new pyright version available (v1.1.301 -> v1.1.365).
Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`

No configuration file found.
pyproject.toml file found at E:\LocalZero\Code\localzero-generator-core.
Loading pyproject.toml file at E:\LocalZero\Code\localzero-generator-core\pyproject.toml
Assuming Python platform Windows
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Searching for source files
Found 202 source files
pyright 1.1.301
0 errors, 0 warnings, 0 informations 
Completed in 25.952sec
============================================================================================================================================= test session starts =============================================================================================================================================
platform win32 -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: E:\LocalZero\Code\localzero-generator-core
plugins: anyio-3.6.2, cov-3.0.0
collected 45 items
tests\test_devtool_commands.py ..............                                                                                                                                                                                                                                                            [ 31%] 
tests\test_end_to_end.py .................                                                                                                                                                                                                                                                               [ 68%] 
tests\test_entries.py .                                                                                                                                                                                                                                                                                  [ 71%] 
tests\test_refdata.py ....                                                                                                                                                                                                                                                                               [ 80%] 
tests\test_tracing.py .........                                                                                                                                                                                                                                                                          [100%] 

============================================================================================================================================= 45 passed in 36.19s ============================================================================================================================================= 
Trim Trailing Whitespace.................................................Passed
Mixed line ending........................................................Passed
Check for case conflicts.................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
Don't commit to branch...................................................Passed
You are ready to rock and save the climate at 60f2c600f0296989a4932e098ab35a63b8771e45, but don't forget to copy paste the above into your pull request

**Comment by bgrundmann** [comment]
> @bgrundmann: I think, there are some further changes in the explorer necessary, because I added the year_baseline to the rpcs as well?! Could you look into the explorer?

I believe you are right that this requires changes to the explorer and also to KNUD.  The changes to the explorer I'll do in this feature.  In KNUD we will have to do as a separate features when this is merged into knud.

Correct me if I'm wrong but this does not actually change the code so that it could handle any baseline other than 2022.  Or let me ask differently would the code do something sensible if the baseline passed in would be different to 2022?  This is still good work, but in that case we should probably add an assert or other check in the code for now.

**Comment by Jeniffere** [comment]
@bgrundmann: That's correct. The code is still not able to handle any baseline other than 2022. But I think it is important to make the baseline year more transparent / visible.

In arguments.py it is ensured, that only 2022 is allowed for the year_baseline_argument. Do you think, that this is enough? Or do you think we need another check deeper within the generator? In that case I think we should add checks for year_ref and year_target as well.

**Comment by Jeniffere** [comment]
@bgrundmann: I added some assertions. See https://github.com/GermanZero-de/localzero-generator-core/pull/394/commits/4ac6dbc2e97dfa4a5d72c825ce59047f46d7c846

**Comment by Jeniffere** [comment]
python devtool.py ready_to_rock
WARNING: there is a new pyright version available (v1.1.301 -> v1.1.368).
Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`

No configuration file found.
pyproject.toml file found at E:\LocalZero\Code\localzero-generator-core.
Loading pyproject.toml file at E:\LocalZero\Code\localzero-generator-core\pyproject.toml
Assuming Python platform Windows
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Searching for source files
Found 203 source files
pyright 1.1.301
0 errors, 0 warnings, 0 informations 
Completed in 18.282sec
=================================================================================================================================== test session starts ====================================================================================================================================
platform win32 -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: E:\LocalZero\Code\localzero-generator-core
plugins: anyio-3.6.2, cov-3.0.0
collected 43 items

tests\test_devtool_commands.py ..............                                                                                                                                                                                                                                         [ 32%]
tests\test_end_to_end.py ...............                                                                                                                                                                                                                                              [ 67%]
tests\test_entries.py .                                                                                                                                                                                                                                                               [ 69%]
tests\test_refdata.py ....                                                                                                                                                                                                                                                            [ 79%]
tests\test_tracing.py .........                                                                                                                                                                                                                                                       [100%]

=================================================================================================================================== 43 passed in 24.24s ==================================================================================================================================== 
Trim Trailing Whitespace.................................................Passed
Mixed line ending........................................................Passed
Check for case conflicts.................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
Don't commit to branch...................................................Passed
black....................................................................Passed
You are ready to rock and save the climate at 4ac6dbc2e97dfa4a5d72c825ce59047f46d7c846, but don't forget to copy paste the above into your pull request

**Pull request merged**
